# @Author: Haibin Lee <haibin>
# @Date:   2020-11-11T16:56:37+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: enterprise.yml
# @Last modified by:   haibin
# @Last modified time: 2020-12-01T13:35:22+08:00
# @License: GNU General Public License v3.0


- name: 前置检查与变量设置
  import_tasks: pre_tasks.yml

- name: 生成机构证书
  include_tasks: generate_agency_certificate.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: agency.name not in agency_existed

- name: 生成机构配置
  include_tasks: generate_agency_config.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: agency.name not in agency_existed

- name: 生成节点连接信息文件
  include_tasks: generate_peers_file.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: agency.name not in agency_existed

- name: 生成创世区块
  include_tasks: generate_genesis.yml
  loop: "{{ agencies | selectattr('create_genesis', 'defined') | selectattr('create_genesis') }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: agency.name not in agency_existed

- name: 生成部署文件
  include_tasks: build_install_package.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: agency.name not in agency_existed

- name: 节点扩展
  include_tasks: expand_node.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when:
    - "'fisco_expand_nodes' in groups"
    - agency.name in agency_existed
    - groups['fisco_expand_nodes'] | regex_search(agency.name)

- name: 安装/配置控制台
  include_tasks: console.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: fisco_console_enabled

- name: 安装/配置 SDK
  include_tasks: sdk.yml
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ agency.name }}"
  when: fisco_sdk_enabled

# - name: 打包部署文件
#   archive:
#     path: "{{ fisco_workdir }}/agency_{{ agency.name }}/fisco_deploy_agency_{{ agency.name }}"
#     dest: "{{ fisco_workdir }}/fisco_deploy_agency_{{ agency.name }}.tgz"
#   loop: "{{ agencies }}"
#   loop_control:
#     loop_var: agency
#     label: "{{ fisco_workdir }}/fisco_deploy_agency_{{ agency.name }}.tgz"
