# @Author: Haibin Lee <haibin>
# @Date:   2020-11-11T16:56:37+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: pre_tasks.yml
# @Last modified by:   haibin
# @Last modified time: 2020-12-07T15:37:44+08:00
# @License: GNU General Public License v3.0



- name: "非国密版 | 检查 generator 目录"
  stat:
    path: "{{ item }}"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __generator_dir
  with_items:
    - "{{ fisco_workdir }}/generator/meta/fisco-bcos"
    - "{{ fisco_workdir }}/generator/dir_agency_ca"
    - "{{ fisco_workdir }}/generator/dir_chain_ca"
  when: not fisco_gm_enabled

- name: "国密版 | 检查 generator 目录"
  stat:
    path: "{{ item }}"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: __generator_dir
  with_items:
    - "{{ fisco_workdir }}/generator/meta/fisco-bcos"
    - "{{ fisco_workdir }}/generator/dir_agency_ca"
    - "{{ fisco_workdir }}/generator/dir_chain_ca"
    - "{{ fisco_workdir }}/generator/dir_chain_ca_normal"
  when: fisco_gm_enabled

- name: 中止执行
  fail:
    msg: "{{ fisco_workdir }}/generator/ 目录初始化不完整，只有 {{ __generator_dir.results | selectattr('stat.exists') | map(attribute='stat.path') | join(', ') }} 存在。某些情况下，generator 目录可能不完整，并且 generator 命令不一定能重新生成。如果不是已经部署的，可以安全删除 {{ fisco_workdir }} 目录，重新执行。如果已经部署了，请到社区里寻求帮助。"
  when:
    - true in __generator_dir.results | map(attribute='stat.exists')
    - false in __generator_dir.results | map(attribute='stat.exists')

- block:
    - include_tasks: install/install_generator.yml
  when: false in __generator_dir.results | map(attribute='stat.exists')

- name: "生成节点清单 {{ fisco_workdir }}/node_list.yml"
  template:
    src: "node_list.j2"
    dest: "{{ fisco_workdir }}/node_list.yml"
    backup: true
  notify: "备份当前 node_list.yml"
  register: __node_list_update

- name: 加载当前节点清单
  include_vars: "{{ fisco_workdir }}/node_list.yml"

- name: 设置动态变量
  set_fact:
    node_list: "{{ node_list | sort }}" # 节点列表重新升序排列，让输出信息比较美观可读。
    pre_node_list_path: "{{ lookup('pipe', 'ls -1tr ' + fisco_workdir + '/node_list.yml.*~ | tail -n1') }}" # 检查 node_list.yml 是否有备份文件。如有，获取文件路径，做新旧节点对比。
    fisco_main_group_id_list: "{{ agencies | map(attribute='main_group_id') | unique }}" # 建立所有群组的 ID 列表。

- name: 检查每个群组是否有且只有 1 个创世区块机构
  fail:
    msg: "群组 {{ item }} 没有指定或存在多个创世区块机构。请排查 {{ inventory_dir }}/group_vars/all/init.yml 文件并确定组内，有且只有 1 个创世区块机构（拥有 create_genesis: true 属性）。"
  loop: "{{ fisco_main_group_id_list }}"
  loop_control:
    label: "检查群组 {{ item }}"
  when: >-
    ( agencies
        | selectattr('main_group_id', '==', item)
        | selectattr('create_genesis', 'defined')
        | selectattr('create_genesis')
        | list
        | count
    ) != 1

- name: 检查机构是否有重名
  fail:
    msg: "机构 {{ item.name }} 有重名，请检查 init.yml 配置。"
  loop: "{{ agencies }}"
  loop_control:
    label: "{{ item.name }}"
  when: >-
    ( agencies
        | selectattr('name', '==', item.name)
        | list
        | count
    ) > 1

- name: 节点分组 | 根据机构名称
  add_host:
    name: "{{ item }}"
    group: "fisco_agency_{{ item.split(':')[0] }}"
  loop: "{{ node_list }}"
  loop_control:
    label: "节点 {{ item.split(':')[2:4] | join(':') }} 添加到 fisco_agency_{{ item.split(':')[0] }} 组"

- name: 节点分组 | 根据 main_group_id 和 extra_group_id
  add_host:
    name: "{{ item.1 }}"
    group: "fisco_node_group_{{ item.0 }}"
  with_nested:
    - "{{ fisco_main_group_id_list }}"
    - "{{ node_list }}"
  loop_control:
    label: "节点 {{ item.1.split(':')[2:4] | join(':') }} 添加到 fisco_group_{{ item.0 }} 组"
  when: >-
    item.0|quote == item.1.split(':')[1]
    or
    item.0|quote in item.1.split(':')[6]

- name: 机构分组 | 根据 main_group_id
  add_host:
    name: "{{ item.name }}"
    group: "fisco_agency_group_{{ item.main_group_id }}"
  loop: "{{ agencies }}"
  loop_control:
    label: "机构 {{ item.name }} 添加到 fisco_agency_group_{{ item.main_group_id }} 组"

- name: 机构分组 | 根据 extra_group_id
  add_host:
    name: "{{ item.0.name }}"
    group: "fisco_agency_group_{{ item.1 }}"
  loop: "{{ agencies | selectattr('extra_group_id', 'defined') | subelements('extra_group_id') }}"
  loop_control:
    label: "机构 {{ item.0.name }} 添加到 fisco_agency_group_{{ item.1 }} 组"

- name: 新增节点加入 'fisco_expand_nodes' 组
  add_host:
    name: "{{ item }}"
    group: "fisco_expand_nodes"
  loop: "{{ node_list }}"
  loop_control:
    label: "{{ item.split(':')[0:4] | join(':') }} 添加到 fisco_expand_nodes 组"
  when:
    - pre_node_list_path is truthy
    - item not in lookup('file', pre_node_list_path)

- name: 检查 extra_group_id 里是否有对应的 main_group_id
  fail:
    msg: “群组 {{ item }} 不存在，请检查 init.yml 的 agencies[*]['extra_group_id'] 是否有对应的 main_group_id。”
  loop: "{{ agencies | selectattr('extra_group_id', 'defined') | sum(attribute='extra_group_id', start=[]) | unique }}"
  loop_control:
    label: "检查群组 {{ item }} 是否存在。"
  when: item not in fisco_main_group_id_list
