# @Author: Haibin Lee <haibin>
# @Date:   2020-11-24T10:45:09+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: generate_archimate.yml
# @Last modified by:   haibin
# @Last modified time: 2021-01-04T14:25:45+08:00
# @Copyright: Copyright 2020 the original author or authors.

- block:
    - name: YUM | 安装 java-1.8.0-openjdk
      package:
        name:
          - java-1.8.0-openjdk
          - graphviz
      when: "ansible_os_family == 'RedHat'"
    - name: APT | 安装 default-jre
      package:
        name:
          - default-jre
          - graphviz
      when: "ansible_os_family == 'Debian'"
    - name: PACMAN | 安装 jre8-openjdk
      package:
        name:
          - jre8-openjdk
          - graphviz
      when: "ansible_os_family == 'Archlinux'"
    - name: 未支持系统
      fail:
        msg: "不支持在当前系统自动安装 JRE，请参考相关方法手动安装。"
      when: "ansible_os_family not in ['Debian', 'RedHat', 'Archlinux']"
  when: lookup('pipe', 'java -version || echo "false"') == 'false'

- block:
    - name: 创建 ~/.local/bin/ 目录
      file:
        path: ~/.local/bin/
        state: directory
    - name: 下载 plantuml
      get_url:
        url: https://sourceforge.net/projects/plantuml/files/plantuml.jar/download
        dest: ~/.local/bin/plantuml.jar
        timeout: 120
        mode: 0644
      register: __plantuml_dl_st
      until: __plantuml_dl_st is succeeded
      retries: 10
      delay: 3
  when: >-
    lookup('pipe', 'stat ~/.local/bin/plantuml.jar || echo "false"') == 'false'

- name: "创建 {{ fisco_workdir }}/archimate 目录"
  file:
    path: "{{ fisco_workdir }}/archimate"
    state: directory
  when: "not lookup('fileglob', fisco_workdir + '/archimate')"

- name: 生成联盟链 puml 文件
  template:
    src: "chain_topo.puml.j2"
    dest: "{{ fisco_workdir }}/archimate/chain_topo.puml"
    validate: "java -jar ~/.local/bin/plantuml.jar -checkonly %s"

- name: 生成机构 puml 文件
  template:
    src: "agency_topo.puml.j2"
    dest: "{{ fisco_workdir }}/archimate/agency_{{ agency.name }}_topo.puml"
    validate: "java -jar ~/.local/bin/plantuml.jar -checkonly %s"
  loop: "{{ agencies }}"
  loop_control:
    loop_var: agency
    label: "{{ fisco_workdir }}/archimate/agency_{{ agency.name }}_topo.puml"

- name: 生成图片文件
  command: "java -jar ~/.local/bin/plantuml.jar -nbthread auto {{ item | basename }}"
  args:
    chdir: "{{ fisco_workdir }}/archimate/"
  changed_when: false
  with_fileglob:
    - "{{ fisco_workdir }}/archimate/*.puml"
  loop_control:
    label: "{{ item | regex_replace('.puml', '.png') }}"

- name: 清理 puml 文件
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ fisco_workdir }}/archimate/*.puml"
